apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n4zqxarin-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n4zqxarin-go 
  name: n4zqxarin-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n4zqxarin-go 
